# -*- coding: utf-8 -*-
"""knn-hadoop-preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17x7gA2oUHKi7hrnghRMxbzHIoD41usiy
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

from sklearn import preprocessing

data = pd.read_csv('shuttle.trn', header = None, sep=' ')

data.head()

data.shape

col9 = data[9]
data2 = data.drop(columns=9)

data2.head()

col9.head()



from sklearn import preprocessing# Get column names first
names = data.columns[:-1]# Create the Scaler object
print(names)
scaler = preprocessing.StandardScaler()# Fit your data on the scaler object
scaled_df = scaler.fit_transform(data2)
scaled_df = pd.DataFrame(scaled_df, columns=names)

scaled_df.head()

scaled_df = scaled_df.join(col9)

scaled_df

scaled_df.to_csv('train.csv', index=False)

data = pd.read_csv('shuttle.tst', header = None, sep=' ')
data3 = data.drop(columns=9)
col9t = data[9]

from sklearn import preprocessing# Get column names first
names = data.columns[:-1]# Create the Scaler object
scaler = preprocessing.StandardScaler()# Fit your data on the scaler object
scaled_df1 = scaler.fit_transform(data3)
scaled_df1 = pd.DataFrame(scaled_df1, columns=names)

scaled_df1.head()

scaled_df1 = scaled_df1.join(col9t)

scaled_df1.to_csv('test2.csv', index = False)

data10 = pd.read_csv('test2.csv')

data10.head()

